version: '3.5'

services:
    app:
        build: ./docker/images/php81
        volumes:
            - ./application:/app
        ports:
            - "6969:8000"
        links:
            - postgresql
        networks:
            - cluster
        restart: always
    postgresql:
        image: postgres:14.1-alpine
        ports:
            - "5431:5432"
        networks:
            - cluster
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: pQLkm8NOkS0gOBox
            POSTGRES_DB: clever
#        volumes:
#            - ./postgres/files/postgresql.conf:/etc/postgresql.conf
#        command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
        restart: always
networks:
    cluster:
        name: cluster
        external: true
        driver: bridge

