version: '3.5'

services:
    app:
        build: ./docker/images/php81
        volumes:
            - ./application:/app
        ports:
            - "6969:8000"
        links:
            - postgresql
        networks:
            - cluster
        restart: always
    postgresql:
        image: postgres:14-alpine3.14
        ports:
            - "5431:5432"
        networks:
            - cluster
        volumes:
            - ./database:/var/lib/postgresql
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: pQLkm8NOkS0gOBox
            POSTGRES_DB: clever
        restart: always
networks:
    cluster:
        name: cluster
        external: true
        driver: bridge

