FROM postgres:13-alpine

#RUN #rm -rf /var/lib/postgres/data
#
#COPY files/postgresql.conf /var/lib/postgresql/data/
#
#RUN #chown postgres:postgres /var/lib/postgresql/data
#
#RUN #postgres initdb -D /var/lib/postgresql/data
